### ISSUE TITLE
Cannot find module 'canvas' on nodeJS version

### ISSUE THREAD

**Issue by Esteezed** [ushelp/EasyQRCodeJS-NodeJS#10]
When installing node-js version I get this error.
Error: Cannot find module 'canvas'

I supposed node-js version should not rely on canvas.

**Comment by ushelp** [comment]
Do you have any good methods to replace canvas to draw images?

**Comment by dashawk** [comment]
I also have issues like this. The exact error that I get is this
```
"Error: Cannot find module '../build/Release/canvas.node'\nRequire stack:\n- /var/task/node_modules/canvas/lib/bindings.js\n- /var/task/node_modules/canvas/lib/canvas.js\n- /var/task/node_modules/canvas/index.js\n- /var/task/node_modules/easyqrcodejs-nodejs/index.min.js\n- /var/task/src/handler/qrcode/generate.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '../build/Release/canvas.node'",
    "Require stack:",
    "- /var/task/node_modules/canvas/lib/bindings.js",
    "- /var/task/node_modules/canvas/lib/canvas.js",
    "- /var/task/node_modules/canvas/index.js",
    "- /var/task/node_modules/easyqrcodejs-nodejs/index.min.js",
    "- /var/task/src/handler/qrcode/generate.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
```

**Comment by ushelp** [comment]
I think you have some issues with the canvas installation. 
please try you can use Canvas first, because draw qrcode image need the library.

**Comment by Esteezed** [comment]
Yes I have an issue with canvas..
Thanks for your response, I 'm gonna put up a server to run it through an API.
very nice module by the way.

I don't know why this solution works for me: 
https://github .com/soldair/node-qrcode/blob/master/package.json
